apiVersion: v1
kind: ServiceAccount
metadata:
  name: coordinator-ksa
  annotations:
    iam.gke.io/gcp-service-account: inference-gke-coord-sa@__PROJECT_ID__.iam.gserviceaccount.com
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: grpc-model-ksa
  annotations:
    iam.gke.io/gcp-service-account: inference-gke-grpc-sa@__PROJECT_ID__.iam.gserviceaccount.com
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: training-service-ksa
  annotations:
    iam.gke.io/gcp-service-account: inference-gke-train-sa@__PROJECT_ID__.iam.gserviceaccount.com
